- name: Install Packages & Setting DB in Debian
  import_tasks: db_debian.yaml
  when: ansible_facts['os_family'] == "Debian"

- name: Install Packages & Setting DB in RedHat
  import_tasks: db_redhat.yaml
  when: ansible_facts['os_family'] == "RedHat"
