- name: Install Packages in Redhat
  yum:
    name: httpd, php, php-mysql, php-gd, php-mbstring
    state: present

- name: Check Httpd Service
  service:
    name: httpd
    state: started
    enabled: yes

- name: Change httpd Service Port
  template:
    src: "{{ wp['port_j2_file'] }}"
    dest: "{{ wp['config_path_redhat'] }}"
    force: yes
  notify:
  - Restart httpd
