- name: Install Packages in Debian
  apt:
    name: apache2, php, php-mysql, php-gd, php-mbstring
    state: present

- name: Check Apache2 Service is Started
  service:
    name: apache2
    state: started
    enabled: yes

- name: Change Apache Service Port
  template:
    src: "{{ wp['port_j2_file'] }}"
    dest: "{{ wp['config_path_debian'] }}"
    force: yes
  notify:
  - Restart apache2    
